// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfig } from '@/lib/supabase-config';

// Obter configuração do Supabase (suporta tanto ambiente integrado quanto clonado)
const config = getSupabaseConfig();

if (!config.isConfigured) {
  console.error('🚨 Supabase Configuration Error:', config.error);
  console.info('📖 Consulte o README.md para instruções de configuração');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(config.url, config.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Função para verificar se o Supabase está configurado
export const isSupabaseConfigured = config.isConfigured;
export const supabaseConfigError = config.error;