// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnqsgjblwuffgpksfyyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucXNnamJsd3VmZmdwa3NmeXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTE4MzUsImV4cCI6MjA2ODAyNzgzNX0.zQEBVwXDClAfZDvefRBKCRKF_ux-GEfzd1QV5iOaxyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});